---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(bayesplot)
library(reshape2)
library(dplyr)
```

# Setting
```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "simulation", "simulations_functions_final.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))

# place for draws
# mac
#posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "multiSims")
# windows
#posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "multiSims")
posterior_draws_path = file.path("F:/", "draws")

#data path
data_save_path = file.path(path_proj, "data", "fitted_model", "simulation", "multiSims", "b_ou")
```

```{r}
#models
q_constant <- file.path(path_proj, "source", "models", 
                      "q-constant.stan")
b_constant <- file.path(path_proj, "source", "models", 
                     "b-constant.stan")
b_rw <- file.path(path_proj, "source", "models", 
                     "b-rw1.stan")
b_ou <-  file.path(path_proj, "source", "models", 
                      "b-ou.stan")

compiled_models <- list(
  q_constant = cmdstan_model(q_constant),
  b_constant = cmdstan_model(b_constant),
  b_rw = cmdstan_model(b_rw),
  b_ou = cmdstan_model(b_ou)
)

models_to_use <- c("q_constant", "b_constant", "b_rw", "b_ou")
```

```{r}
###### setting #####
# set seed to replicate
seed <- 123
set.seed(seed)
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
T = 60
# reprot delay
D <- 15;

# Time period for checking
D_check <- 5

# number of simulations
num_sims <- 100

first_date <- as.Date("2024-01-01")

scoreRange <- c(first_date+days(9), first_date+days(19), first_date+days(29),
                first_date+days(39), first_date+days(49))
```

## Fully reported case

### Simulation
```{r}
b_ou_FR_multi <- list()
# generate
for (i in 1:num_sims) {
  b_ou_FR_multi[[i]] <- simulateData(
        params <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "b_ou",
    method_params = list(theta_logb = 0.3, mu_logb = log(0.7), init_logb = log(0.7), sigma_logb = 0.2,
                         theta_logitphi = 0.3, mu_logitphi = 1, init_logitphi = 1, sigma_logitphi = 0.2)
  )
)
  )
}

par(mfrow = c(2, 1))
plot(b_ou_FR_multi[[1]]$b, pch = 19, type = "b")
plot(b_ou_FR_multi[[1]]$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(b_ou_FR_multi[[1]]$q), type = "l", lty = 1, ylim = c(0, 1))

```


### Exploratory analysis
```{r}
# exploritary analysis
page_num <- ceiling(nrow(b_ou_FR_multi[[1]]$case_reported_cumulated)/16)
exp_plot_b_ou <- fit_exp_plot(b_ou_FR_multi[[1]]$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
# print(exp_plot_b_ou)
# 
# exp_plot_b_ou$coefficients
exp_b_data_b_ou<- data.frame( date = as.Date(rownames(b_ou_FR_multi[[1]]$case_reported_cumulated)),
                          b = exp_plot_b_ou$coefficients$b)

exp_b_plot_b_ou <- ggplot(exp_b_data_b_ou, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_b_ou)
```


### Model fitting
```{r}
# out_b_ou_FR_multi <- list()
# for (i in 1:num_sims) {
#   print(paste0("Now is working on ",i,"th simulation."))
#   out_b_ou_FR_multi[[i]] <- 
#     nowcasting_moving_window(b_ou_FR_multi[[i]]$case_reported_cumulated, scoreRange =  scoreRange,
#                           case_true = b_ou_FR_multi[[i]]$case_true,
#                           start_date = first_date,
#                           D = D,
#                           methods =models_to_use,
#                           compiled_models = compiled_models,
#                           iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
#                           num_chains = 3, suppress_output = T,
#                           posterior_draws_path = file.path(posterior_draws_path, "b_ou","FR")
#                           )
# }
# 
# save(out_b_ou_FR_multi, file = file.path(data_save_path, "FR_b_ou_multi.RData"))
load( file.path(data_save_path, "FR_b_ou_multi.RData"))

# Result table to generate metrics
results_b_ou_FR <- compute_all_nowcasts_tables(out_b_ou_FR_multi, D, "day", models_to_use)

save(results_b_ou_FR, file = file.path(data_save_path, "FR_b_ou_multi_result.RData"))
load( file.path(data_save_path, "FR_b_ou_multi_result.RData"))
# Average metrics
metrics_1_b_ou_FR_avg <- average_nowcasts_metrics(
  results_all   = results_b_ou_FR,
  methods       =  models_to_use,
  filter_length = 15 #nowcasting length
)

metrics_1_b_ou_FR_avg

# Average metrics for most recent days
metrics_1_b_ou_FR_avg_incomp <- average_nowcasts_metrics(
  results_all   = results_b_ou_FR,
  methods       = models_to_use,
  filter_length = D_check
) 
metrics_1_b_ou_FR_avg_incomp

#
results_b_ou_FR_1 <- nowcasts_table(out_b_ou_FR_multi[[1]], D = D, report_unit = "day", 
                          methods = models_to_use)

plots_b_ou_FR <- nowcasts_plot(results_b_ou_FR_1, D = D, report_unit = "day", methods = models_to_use)
plots_b_ou_FR
```   
## Not fully reported case

### Simulation
```{r}
set.seed(seed)

b_ou_NFR_multi <- list()
# generate
for (i in 1:num_sims) {
  b_ou_NFR_multi[[i]] <- simulateData(
        params <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "b_ou",
    method_params = list(theta_logb = 0.2, mu_logb = log(0.2), init_logb = log(0.2), sigma_logb = 0.15,
                         theta_logitphi = 0.2, mu_logitphi = 1.5, init_logitphi = 1.5, sigma_logitphi = 0.15)
  )
)
  )
}

par(mfrow = c(2, 1))
plot(b_ou_NFR_multi[[1]]$b, pch = 19, type = "b")
plot(b_ou_NFR_multi[[1]]$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(b_ou_NFR_multi[[1]]$q), type = "l", lty = 1, ylim = c(0, 1))
```

### Exploratory analysis
```{r}
# exploritary analysis
page_num <- ceiling(nrow(b_ou_NFR_multi[[1]]$case_reported_cumulated)/16)
exp_plot_b_ou <- fit_exp_plot(b_ou_NFR_multi[[1]]$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
# print(exp_plot_b_ou)
# 
# exp_plot_b_ou$coefficients
exp_b_data_b_ou<- data.frame( date = as.Date(rownames(b_ou_NFR_multi[[1]]$case_reported_cumulated)),
                          b = exp_plot_b_ou$coefficients$b)

exp_b_plot_b_ou <- ggplot(exp_b_data_b_ou, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_b_ou)
```



### Model fitting
```{r}
out_b_ou_NFR_multi <- list()
# for (i in 1:num_sims) {
#   print(paste0("Now is working on ",i,"th simulation."))
#   out_b_ou_NFR_multi[[i]] <- 
#     nowcasting_moving_window(b_ou_NFR_multi[[i]]$case_reported_cumulated, scoreRange =  scoreRange,
#                           case_true = b_ou_NFR_multi[[i]]$case_true,
#                           start_date = first_date,
#                           D = D,
#                           methods =models_to_use,
#                           compiled_models = compiled_models,
#                           iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
#                           num_chains = 3, suppress_output = T,
#                           posterior_draws_path = file.path(posterior_draws_path, "b_ou","NFR")
#                           )
# }
# 
# save(out_b_ou_NFR_multi, file = file.path(data_save_path, "NFR_b_ou_multi.RData"))
load( file.path(data_save_path, "NFR_b_ou_multi.RData"))

# Result table to generate metrics
# results_b_ou_NFR <- compute_all_nowcasts_tables(out_b_ou_NFR_multi, D, "day", models_to_use)
# 
# save(results_b_ou_NFR, file = file.path(data_save_path, "NFR_b_ou_multi_result.RData"))
load( file.path(data_save_path, "NFR_b_ou_multi_result.RData"))
# Average metrics
metrics_1_b_ou_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_b_ou_NFR,
  methods       =  models_to_use,
  filter_length = 15 #nowcasting length
)

metrics_1_b_ou_NFR_avg

# Average metrics for most recent days
metrics_1_b_ou_NFR_avg_incomp <- average_nowcasts_metrics(
  results_all   = results_b_ou_NFR,
  methods       = models_to_use,
  filter_length = D_check
) 
metrics_1_b_ou_NFR_avg_incomp

#
results_b_ou_NFR_1 <- nowcasts_table(out_b_ou_NFR_multi[[1]], D = D, report_unit = "day", 
                          methods = models_to_use)

plots_b_ou_NFR <- nowcasts_plot(results_b_ou_NFR_1, D = D, report_unit = "day", methods = models_to_use)
plots_b_ou_NFR

# plots_b_ou_NFR_separated <- nowcasts_plot_separated(results_b_ou_NFR, D = D, report_unit = "day", methods = models_to_use)
# plots_b_ou_NFR_separated
```   

## Result generate
```{r}
results_b_ou_NFR <- compute_all_nowcasts_tables(out_b_ou_NFR_multi, D, "day", models_to_use)
# Average metrics
metrics_1_b_ou_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_b_ou_NFR,
  methods       =  models_to_use
)

metrics_1_b_ou_NFR_avg

# Average metrics for most recent days
metrics_1_b_ou_NFR_avg_incomp <- average_nowcasts_metrics(
  results_all   = results_b_ou_NFR,
  methods       = models_to_use,
  filter_length = D_check
) 
metrics_1_b_ou_NFR_avg_incomp

#
results_b_ou_NFR <- nowcasts_table(out_b_ou_NFR_multi[[1]], D = D, report_unit = "day", 
                          methods = models_to_use)

plots_b_ou_NFR <- nowcasts_plot(results_b_ou_NFR, D = D, report_unit = "day", methods = models_to_use)
plots_b_ou_NFR
```

### Metrics table
```{r}
highlight_metrics(metrics_1_b_ou_FR_avg, method_names = c("Constant q", "Constant b", "Randow Walk b","OU b"), date_labels = scoreRange, table_caption = "Fully Reported + OU b (All nowcast window)")

highlight_metrics(metrics_1_b_ou_FR_avg_incomp, method_names = c("Constant q", "Constant b", "Randow Walk b", "OU b"), date_labels = scoreRange, table_caption = "Fully Reported + OU b (Last 5 days)")
```

```{r}
highlight_metrics(metrics_1_b_ou_NFR_avg, method_names = c("Constant q", "Constant b", "Randow Walk b", "OU b"), date_labels = scoreRange,
                  table_caption = "Not Fully Reported + OU b (All nowcast window)")
highlight_metrics(metrics_1_b_ou_NFR_avg_incomp, method_names = c("Constant q", "Constant b", "Randow Walk b", "OU b"), date_labels = scoreRange,
                  table_caption = "Not Fully Reported + OU b (Last 5 days)")
```

### Plots
```{r}
plots_b_ou_FR <- nowcasts_plot(results_b_ou_FR, D = D, report_unit = "day", methods = models_to_use,
                                  combine_plots = T, ncol=1, nrow = 5)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_ou", "FR_b_ou.png"),
       plot = plots_b_ou_FR,
       width = 10, height = 16, dpi = 300)

plots_b_ou_FR_separated <- nowcasts_plot_separated(results_b_ou_FR_1, D = D, report_unit = "day", methods = models_to_use, combine_plots = T)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_ou", "FR_b_ou_separated.png"),
       plot = plots_b_ou_FR_separated,
       width = 30, height = 22, dpi = 300)
```

```{r}
plots_b_ou_NFR <- nowcasts_plot(results_b_ou_NFR, D = D, report_unit = "day", methods = models_to_use,
                                  combine_plots = T, ncol=1, nrow = 5)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_ou", "NFR_b_ou.png"),
       plot = plots_b_ou_NFR,
       width = 10, height = 16, dpi = 300)

plots_b_ou_NFR_separated <- nowcasts_plot_separated(results_b_ou_NFR_1, D = D, report_unit = "day", methods = models_to_use, combine_plots = T)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "b_ou", "NFR_b_ou_separated.png"),
       plot = plots_b_ou_NFR_separated,
       width = 30, height = 22, dpi = 300)
```