---
title: "MovingWindowSims"
author: "Yang Xiao"
date: "2024-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE)

library(rstan)
# library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(aweek)
library(lubridate)

#remotes::install_github("stan-dev/cmdstanr")
library(cmdstanr)
# cmdstanr::check_cmdstan_toolchain(fix = TRUE)
# install_cmdstan(cores = 4, overwrite = TRUE)
# set_cmdstan_path(path = "C:/Users/Administrator/.cmdstan/cmdstan-2.35.0")
# cmdstan_version()
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

# source
source(file.path(path_source, "simulation", "simulations_functions_final.R"))
# source from other paper
source(file.path(path_source, "funcs_german_paper", "plotReportingTriangle.R"))

```

```{r}
fixed_q <- file.path(path_proj, "source", "models",
                     "trunc", "1.stan_model_fixed_q_trunc.stan")
fixed_b <- file.path(path_proj, "source", "models",
                     "trunc", "2.stan_model_fixed_b_trunc.stan")
b_poly <- file.path(path_proj, "source", "models", "trunc",
                     "3.stan_model_b_poly_trunc.stan")
b_spline <- file.path(path_proj, "source", "models", "trunc",
                     "4.stan_model_b_spline_trunc.stan")

compiled_models <- list(
  fixed_q = cmdstan_model(fixed_q),
  fixed_b = cmdstan_model(fixed_b),
  b_poly = cmdstan_model(b_poly),
  b_spline = cmdstan_model(b_spline)
)

```

```{r, warning=FALSE}
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))
source(file.path(path_source, "functions", "tidy_dengueBR.R"))


# setting: delay,  number of days
seed <- 123
D <- 10

# try-on AC
root_dir <- "/Users/xiaoy0a/Desktop/GitHub/Dengue/dengue-tracker/data/weekly_data/infodengue"

AC_EW10_to_EW39 <- get_infodengue_data(root_dir, start = "202410", end = "202439", states = "AC", D = 10, fill_missing = T)$AC
AC_EW10_to_EW39[15,1] <- AC_EW10_to_EW39[14,1]

# 2024-03-03 to 2024-12-08
scoreRange <- seq(as.Date("2024-04-14"),as.Date("2024-09-22"),by="28 day")

# input the true case vector
AC_data <- read.csv(file.path(root_dir,"202449","AC_2024-12-08_infodengue.csv")) %>% filter(ew >= 202410 & ew <= 202439) %>% 
  select(ew_start, sum_of_cases)

case_true <- as.matrix(AC_data$sum_of_cases)
rownames(case_true) <- as.character(AC_data$ew_start)
```

```{r}
AC_matrix_for_plot <- AC_EW10_to_EW39[as.Date(rownames(AC_EW10_to_EW39)) <= (max(as.Date(rownames(AC_EW10_to_EW39))) - D*7),]


page_num <- ceiling(nrow(AC_matrix_for_plot)/16)

AC_exp_plot <- fit_exp_plot(AC_matrix_for_plot,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)

AC_exp_plot$coefficients
```

```{r}
AC_exp_b_data <- data.frame( date = as.Date(rownames(AC_matrix_for_plot)),
                          b = AC_exp_plot$coefficients)

AC_exp_b_plot <- ggplot(AC_exp_b_data, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

AC_exp_b_plot
```

```{r}
out <- nowcasting_moving_window(AC_EW10_to_EW39, scoreRange = as.Date("2024-09-01"), 
                                case_true = case_true,
                                start_date = as.Date("2024-03-03"),
                                #start_date = scoreRange[1] - weeks(20),
                                D = 10, sigma_b = 0.5, seeds = seed,
                                models_to_run = c("fixed_q", "fixed_b", "b_poly","b_spline"),
                                compiled_models = compiled_models,
                                iter_sampling = 3000, iter_warmup = 1000, refresh = 500,
                                num_chains = 3, suppress_output = T)

save(out, file = file.path(path_proj, "data", "fitted_model","AC_EW10_to_EW39.RData"))
out <- load(file.path(path_proj, "data", "fitted_model","SARI_090705_to_100606_seven.RData"))
results <- nowcasts_plot(out, D = 26, report_unit = "week", 
                         models_to_run = c("fixed_q", "fixed_b", "b_poly", "b_spline"))
```

```{r}
print(scoreRange)
for(i in 1:length(scoreRange)){
  print(calculate_metrics(results$nowcasts[i][[1]]))
}
```


```{r}
nowcasts_plot(out,D = 26, report_unit = "week",  models_to_run = c("fixed_q", "b_spline"))[["plots"]]
```

```{r}
nowcasts_plot(out,D = 26, report_unit = "week")[["plots"]]
```


```{r}
nowcasts_plot(out,D = 26, report_unit = "week",  models_to_run = c("fixed_q"))[["plots"]]
```

```{r}
nowcasts_plot(out,D = 26, report_unit = "week",  models_to_run = c("fixed_b"))[["plots"]]
```

```{r}
nowcasts_plot(out,D = 26, report_unit = "week",  models_to_run = c("b_poly"))[["plots"]]
```

```{r}
nowcasts_plot(out,D = 26, report_unit = "week",  models_to_run = c("b_spline"))[["plots"]]
```