---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")
```



## simuoate data

```{r}
source(file.path(path_source, "simulation", "simulations_functions.R"))

# setting: delay,  number of days
seed <- 123
D <- 15
N_obs <- 58
num_sims <- 1000

# constant b = 3
b_true <- 0.5
q <- simsQ("constant", b = b_true)$qd

p <- c(q[1], diff(q))
plot(p, type = "b", xlab = expression("Delay"),  
     ylab = expression("Report proportion"))

q <- cumsum(p)
plot(q, type = "b", xlab = expression("Delay"),  
     ylab = expression("Accumulated report proportion"))

```

### generate data
```{r}
data <- simsDataGenQ(days = N_obs, method = "constant", b = b_true,
                     seed = seed)

# create triangular data
data_trunc <- create_triangular_data(data$case_reported)

# get indices of non-NAs 
indices_data_trunc <- find_non_na_coords(data_trunc)

data_trunc[is.na(data_trunc)] <- 0   
print(data_trunc)
```

## fit model
```{r}
stan_data_trunc <- list(N_obs = N_obs, D = D + 1, Y = data_trunc,
                        K = nrow(indices_data_trunc), obs_index = indices_data_trunc)

fit_trunc <- stan(
  file = file.path(path_proj, "source", "models", "trunc",
                   "stan_model_time-ind-expgrowth-trunc.stan"),  
  data = stan_data_trunc, 
  iter = 2000, chains = 3, seed = 123
)

1 - exp(- 0.6 * 1:16)
```


## check results
```{r}
print(fit_trunc)
```

```{r}
library(ggplot2)
plot(fit_trunc, pars = c("b")) +
  geom_point(aes(x, y), data = data.frame(x = round(b_true,2), y = c(1)), color = "blue")
```