---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
```


```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")
```



## simuoate dat

```{r}
source(file.path(path_source, "simulation", "simulations_functions.R"))

# setting: delay,  number of days
seed <- 123
D <- 15
N_obs <- 58
num_sims <- 1

# time varying b
beta0 = -2 ; beta1 = 0.01
data <- simsDataGenQ(alpha = c(1:10, seq(1, 232, by = 4)),
                     days = N_obs, method = "random_walk",
                     b = 0.1, sigma_rw = 0.1, seed = seed)

data$case_reported
```
### basis for spline
```{r}

time_points <- 1:N_obs

n_knots <- 5
knot_dist <- 1 / (n_knots + 1)
probs <- seq(knot_dist, 1 - knot_dist, by = knot_dist)
knots <- quantile(time_points, probs = probs)

spline_basis <- bs(time_points, knots = knots, degree = 3, intercept = TRUE)
X_spline <- cbind(1, as.matrix(spline_basis))

# 
basis_df <- data.frame(time = time_points, X_spline)
basis_long <- reshape2::melt(basis_df, id.vars = "time")

ggplot(basis_long, aes(x = time, y = value, color = variable)) +
  geom_line() +
  labs(title = "B-spline Basis Functions for Time",
       x = "Time (Days)",
       y = "Basis Value") +
  theme_minimal()
```

## fit model
```{r}
stan_data <- list(N_obs = N_obs, D = D + 1, 
                  J = ncol(X_spline),
                  X_spline = X_spline,
                  Y = round(data$case_reported))

# init_values <- list(
#   list(lambda_t = rep(1, N_obs), b_t = rep(0.1, N_obs)),  # Chain 1
#   list(lambda_t = rep(2, N_obs), b_t = rep(0.1, N_obs)),  # Chain 2
#   list(lambda_t = rep(3, N_obs), b_t = rep(0.1, N_obs))  # Chain 3
# )


fit <- stan(
  file = file.path(path_proj, "source", "models", "stan_model_dep-spline.stan"),  
  data = stan_data, 
  iter = 2000, chains = 3, seed = 123
  #init = init_values
)
```


## check results
```{r}
print(fit, pars = "beta")


print(fit, pars = "N_t")
```

```{r}
library(ggplot2)
plot(fit, par = c("b_t_est")) +
  geom_point(aes(x, y), data = data.frame(x = data$b, y = c(58:1)), color = "blue")
```

```{r}
plot(fit, par = c("N_t")) +
  geom_point(aes(x, y), data = data.frame(x = data$case_true, y = c(58:1)), color = "blue")
```


