---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
```


```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "simulation", "simulations_functions_final.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))
```

```{r}
#models
fixed_q <- file.path(path_proj, "source", "models",
                      "1.stan_model_fixed_q_trunc.stan")
fixed_b <- file.path(path_proj, "source", "models",
                     "2.stan_model_fixed_b_trunc.stan")
linear_b <- file.path(path_proj, "source", "models", 
                     "3.stan_model_linear_b_trunc.stan")
ou_b <-  file.path(path_proj, "source", "models",
                      "4.stan_model_ou_b_trunc.stan")

compiled_models <- list(
  fixed_q = cmdstan_model(fixed_q),
  fixed_b = cmdstan_model(fixed_b),
  linear_b = cmdstan_model(linear_b),
  ou_b = cmdstan_model(ou_b)
)
```


## simulate data

### settings and data
```{r}
###### setting #####
seed <- 123
set.seed(seed)

num_sims <- 10
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
n_obs = 60
# reprot structure
D <- 10; D_complete <- 20; if_fully_reported <- F
# model
method = "ou_b"; 
alpha_ou=0.4; mu_ou=0.1; b_init=0.1; 
# sd changes for each scenario
sigma_ou_1 = 0.01; sigma_ou_2 = 0.1; sigma_ou_3 = 0.3

# input list
params_1 <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = method,
    method_params = list(alpha = alpha_ou, mu = mu_ou, 
                         b_init = b_init, sigma_ou = sigma_ou_1)
  )
)
# date that we run
scoreRange <- seq(as.Date("2024-01-15"),as.Date("2024-02-29"),by="14 day")
#scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"), as.Date("2024-02-26"))

#scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"))

NFR_1 <- list()
# generate
for (i in 1:num_sims) {
  NFR_1[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_1)
      )
    )
  )
}
```


```{r}
# input list
NFR_2 <- list()
# generate
for (i in 1:num_sims) {
  NFR_2[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_2)
      )
    )
  )
}
```


```{r}
# input list
NFR_3 <- list()
# generate
for (i in 1:num_sims) {
  NFR_3[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_3)
      )
    )
  )
}
```


## fit model
```{r}
out_list_1_NFR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_1_NFR[[i]] <-
    nowcasting_moving_window(NFR_1[[i]]$case_reported, scoreRange = scoreRange,
                                case_true = NFR_1[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T,
                             posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "10sims-Jan6"))
}

save(out_list_1_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims10.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))

# results_1_NFR_plots <- nowcasts_plot(results_1_NFR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```   

```{r}
out_list_2_NFR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_2_NFR[[i]] <- 
    nowcasting_moving_window(NFR_2[[i]]$case_reported, scoreRange = scoreRange, 
                                case_true = NFR_2[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T,
                             posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "10sims-Jan6"))
}

save(out_list_2_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd01_sims10.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd01_sims5.RData"))

# results_1_NFR_plots <- nowcasts_plot(results_1_NFR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```

```{r}
out_list_3_NFR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_3_NFR[[i]] <- 
    nowcasting_moving_window(NFR_3[[i]]$case_reported, scoreRange = scoreRange, 
                                case_true = NFR_3[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T,
                             posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "10sims-Jan6"))
}

save(out_list_3_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd03_sims10.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd03_sims5.RData"))


# results_1_NFR_plots <- nowcasts_plot(results_1_NFR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```

```{r}
results_1_NFR <- compute_all_nowcasts_tables(out_list_1_NFR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
# results_1_NFR_avg <- average_nowcasts_tables(results_1_NFR)
# 


# Average metrics
metrics_1_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_1_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_1_NFR_avg

# Average metrics
metrics_1_NFR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_1_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_1_NFR_avg_incomplete


highlight_metrics(metrics_1_NFR_avg, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + Low Variability (All Time Window)")
highlight_metrics(metrics_1_NFR_avg_incomplete, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + Low Variability (Last D Time Unit)")
#
# for (t in seq_along(metrics_1_NFR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_1_NFR_avg[[t]])
# }
```


```{r}
results_2_NFR <- compute_all_nowcasts_tables(out_list_2_NFR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
# results_2_NFR_avg <- average_nowcasts_tables(results_2_NFR)
# 


# Average metrics
metrics_2_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_2_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_2_NFR_avg

# Average metrics
metrics_2_NFR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_2_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_2_NFR_avg_incomplete

highlight_metrics(metrics_2_NFR_avg, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + Moderate Variability (All Time Window)")
highlight_metrics(metrics_2_NFR_avg_incomplete, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + Moderate Variability (Last D Time Unit)")

#
# for (t in seq_along(metrics_2_NFR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_2_NFR_avg[[t]])
# }
```

```{r}
results_3_NFR <- compute_all_nowcasts_tables(out_list_3_NFR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
#results_3_NFR_avg <- average_nowcasts_tables(results_3_NFR)


# Average metrics
metrics_3_NFR_avg <- average_nowcasts_metrics(
  results_all   = results_3_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_3_NFR_avg

# Average metrics
metrics_3_NFR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_3_NFR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_3_NFR_avg_incomplete

highlight_metrics(metrics_3_NFR_avg, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + High Variability (All Time Window)")
highlight_metrics(metrics_3_NFR_avg_incomplete, method_names = c("Fixed q", "Fixed b", "Linear b", "OU b"),
                  table_caption = "Not Fully Reported + High Variability (Last D Time Unit)")

#
# for (t in seq_along(metrics_3_NFR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_3_NFR_avg[[t]])
# }
```





```{r}

plots_1_NFR <- nowcasts_plot(
  nowcasts_list = results_1_NFR[[1]],
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = NULL
)

plots_2_NFR <- nowcasts_plot(
  nowcasts_list = results_2_NFR[[1]],
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = NULL
)

plots_3_NFR <- nowcasts_plot(
  nowcasts_list = results_3_NFR[[1]],
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = NULL
)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NFR_b01_sd001.png"), 
       plot = plots_1_NFR, 
       width = 10, height = 12, dpi = 300)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NFR_b01_sd01.png"), 
       plot = plots_2_NFR, 
       width = 10, height = 12, dpi = 300)

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NFR_b01_sd03.png"), 
       plot = plots_3_NFR, 
       width = 10, height = 12, dpi = 300)

```


# output
```{r}
results_1_NFR_plots <- nowcasts_plot(results_1_NFR, D = D, report_unit = "day",
                                 models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"),
                                 combine_plots = T, ncol = 2
                                 )

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NotFR_b01_sd001.png"), 
       plot = results_1_NFR_plots, 
       width = 10, height = 12, dpi = 300)
# table
fully_tables_1 <- list();count_1 = 1
for (i in 1:length(scoreRange)) {
  fully_tables_1[[count_1]] <- calculate_metrics(results_1_NFR[[i]])
  count_1 = count_1 + 1
}
cat(highlight_metrics(fully_tables_1, method_names =c("Fixed q", "Fixed b", "Polynomial b" , "Random Walk b"),
                  date_labels = as.character(scoreRange)))

```


```{r}
results_2_NFR_plots <- nowcasts_plot(results_2_NFR, D = D, report_unit = "day",
                                 models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"),
                                 combine_plots = T, ncol = 2
                                 )

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NotFR_b01_sd01.png"), 
       plot = results_2_NFR_plots, 
       width = 10, height = 12, dpi = 300)
# table
fully_tables_2 <- list();count_2 = 1
for (i in 1:length(scoreRange)) {
  fully_tables_2[[count_2]] <- calculate_metrics(results_2_NFR[[i]])
  count_2 = count_2 + 1
}
cat(highlight_metrics(fully_tables_2, method_names =c("Fixed q", "Fixed b", "Polynomial b" , "Random Walk b"),
                  date_labels = as.character(scoreRange)))

```

```{r}
results_3_NFR_plots <- nowcasts_plot(results_3_NFR, D = D, report_unit = "day",
                                 models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"),
                                 combine_plots = T, ncol = 2
                                 )

ggsave(filename = file.path(path_proj, "plots_to_show", "simulation", "NotFR_b01_sd03.png"), 
       plot = results_3_NFR_plots, 
       width = 10, height = 12, dpi = 300)
# table
fully_tables_3 <- list();count_3 = 1
for (i in 1:length(scoreRange)) {
  fully_tables_3[[count_3]] <- calculate_metrics(results_3_NFR[[i]])
  count_3 = count_3 + 1
}
cat(highlight_metrics(fully_tables_3, method_names =c("Fixed q", "Fixed b", "Polynomial b" , "Random Walk b"),
                  date_labels = as.character(scoreRange)))

```