---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
```


```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "simulation", "simulations_functions_final.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))

# place for draws
# mac
#posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "testEach")
# windows
posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "testEach")

#data path
data_save_path = file.path(path_proj, "data", "fitted_model", "simulation", "2. fixed_b")
```

```{r}
#models
fixed_q <- file.path(path_proj, "source", "models", 
                      "1.stan_model_fixed_q.stan")
fixed_b <- file.path(path_proj, "source", "models", 
                     "2.stan_model_fixed_b.stan")
rw_b <- file.path(path_proj, "source", "models", 
                     "5.stan_model_rw_b_logis.stan")
ou_b <-  file.path(path_proj, "source", "models", 
                      "6.stan_model_ou_b_logis.stan")

compiled_models <- list(
  fixed_q = cmdstan_model(fixed_q),
  fixed_b = cmdstan_model(fixed_b),
  #rw_b = cmdstan_model(rw_b),
  ou_b = cmdstan_model(ou_b)
)

# models_to_use <- c("fixed_b", "fixed_b", "rw_b", "ou_b")
models_to_use <- c("fixed_q", "fixed_b",  "ou_b")
```


## simulate data - FR

### setting
```{r}
###### setting #####
seed <- 123
set.seed(seed)

# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
N_obs = 60
# reprot delay
D <- 15;

# Time period for checking
D_check <- 5

scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"), as.Date("2024-02-26"))
```

```{r}
# fixed_b_FR
params_fixed_b_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    N_obs       = N_obs,
    date_start = as.Date("2024-01-01"),
    D = D,
    seed       = seed
  ),
  q_model = list(
    method        = "fixed_b",
    method_params = list(b = 0.4, phi = 0.2)
  )
)

fixed_b_FR <- simulateData(params_fixed_b_FR)

```

```{r}
# fixed_b_NFR
params_fixed_b_NFR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    N_obs       = N_obs,
    date_start = as.Date("2024-01-01"),
    D = D,
    seed       = seed
  ),
  q_model = list(
    method        = "fixed_b",
    method_params = list(b = 0.1, phi = 0.1)
  )
)

fixed_b_NFR <- simulateData(params_fixed_b_NFR)

```

## expplot
```{r}
# exploritary analysis
page_num <- ceiling(nrow(fixed_b_FR$case_reported_cumulated)/16)
exp_plot_fixed_b <- fit_exp_plot(fixed_b_FR$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
print(exp_plot_fixed_b)

exp_plot_fixed_b$coefficients
exp_b_data_fixed_b<- data.frame( date = as.Date(rownames(fixed_b_FR$case_reported_cumulated)),
                          b = exp_plot_fixed_b$coefficients$b)

exp_b_plot_fixed_b <- ggplot(exp_b_data_fixed_b, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_fixed_b)

```


```{r}
# exploritary analysis
page_num <- ceiling(nrow(fixed_b_NFR$case_reported_cumulated)/16)
exp_plot_fixed_b <- fit_exp_plot(fixed_b_NFR$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
print(exp_plot_fixed_b)

exp_plot_fixed_b$coefficients
exp_b_data_fixed_b<- data.frame( date = as.Date(rownames(fixed_b_NFR$case_reported_cumulated)),
                          b = exp_plot_fixed_b$coefficients$b)

exp_b_plot_fixed_b <- ggplot(exp_b_data_fixed_b, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +       
  geom_smooth(method = "loess", se = TRUE,        
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")

print(exp_b_plot_fixed_b)

```

## fit model
```{r}
out_fixed_b_FR <- nowcasting_moving_window(fixed_b_FR$case_reported_cumulated, scoreRange =  scoreRange,
                          case_true = fixed_b_FR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          methods =models_to_use,
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T,
                          posterior_draws_path = file.path(posterior_draws_path, "fixed_b")
                          )


save(out_fixed_b_FR, file = file.path(data_save_path, "FR_fixed_b.RData"))
#load( file.path(data_save_path, "FR_fixed_b.RData"))
# 
results_fixed_b_FR <- nowcasts_table(out_fixed_b_FR, D = D, report_unit = "day",
                          methods = models_to_use
                          )

plots_fixed_b_FR <- nowcasts_plot(results_fixed_b_FR, D = D, report_unit = "day",
                                  methods = models_to_use
                                  )

for (i in 1:length(results_fixed_b_FR)) {
  print(calculate_metrics(results_fixed_b_FR[[i]],
                          methods = models_to_use))
}

for (i in 1:length(results_fixed_b_FR)) {
  print(calculate_metrics(data.table::last(results_fixed_b_FR[[i]], D_check),
                          methods = models_to_use))
}

plots_fixed_b_FR
```   

```{r}
out_fixed_b_NFR <- nowcasting_moving_window(fixed_b_NFR$case_reported_cumulated, scoreRange = scoreRange,
                          case_true = fixed_b_NFR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          methods =models_to_use,
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T,
                          posterior_draws_path = file.path(posterior_draws_path, "fixed_b")
                          )


save(out_fixed_b_NFR, file = file.path(data_save_path, "NFR_fixed_b.RData"))
#load( file.path(data_save_path, "NFR_fixed_b.RData"))

results_fixed_b_NFR <- nowcasts_table(out_fixed_b_NFR, D = D, report_unit = "day", 
                          methods = models_to_use
                          )

plots_fixed_b_NFR <- nowcasts_plot(results_fixed_b_NFR, D = D, report_unit = "day", 
                                  methods = models_to_use
                                  )

for (i in 1:length(results_fixed_b_NFR)) {
  print(calculate_metrics(results_fixed_b_NFR[[i]],
                          methods = models_to_use))
}

for (i in 1:length(results_fixed_b_NFR)) {
  print(calculate_metrics(data.table::last(results_fixed_b_NFR[[i]],D_check),
                          methods = models_to_use))
}

plots_fixed_b_NFR
```   