---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
```


```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

# source(file.path(path_source, "simulation", "simulations_functions.R"))
source(file.path(path_source, "simulation", "simulations_functions_final.R"))

source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))
```

```{r}
#models
fixed_q <- file.path(path_proj, "source", "models",
                     "trunc", "1.stan_model_fixed_q_trunc.stan")
fixed_b <- file.path(path_proj, "source", "models",
                     "trunc", "2.stan_model_fixed_b_trunc.stan")
linear_b <- file.path(path_proj, "source", "models", "trunc",
                     "3.stan_model_linear_b_trunc.stan")
# ou_b <- file.path(path_proj, "source", "models", "trunc",
#                      "4.stan_model_ou_b_trunc.stan")

ou_b <-  file.path(path_proj, "source", "models", "trunc",
                      "4.stan_model_ou_b_trunc.stan")

compiled_models <- list(
  fixed_q = cmdstan_model(fixed_q),
  fixed_b = cmdstan_model(fixed_b),
  linear_b = cmdstan_model(linear_b),
  ou_b = cmdstan_model(ou_b)
)
```


## simulate data

### settings and data
```{r}
###### setting #####
seed <- 123
set.seed(seed)

num_sims <- 5
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
n_obs = 60
# reprot structure
D <- 10; D_complete <- 20; if_fully_reported <- T
# model
method = "ou"; 
alpha_ou=0.4; mu_ou=0.5; b_init=0.5; 
# sd changes for each scenario
sigma_ou_1 = 0.01; sigma_ou_2 = 0.1; sigma_ou_3 = 0.3

# input list
params_1 <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = method,
    method_params = list(alpha = alpha_ou, mu = mu_ou, 
                         b_init = b_init, sigma_ou = sigma_ou_1)
  )
)
# date that we run
scoreRange <- seq(as.Date("2024-01-15"),as.Date("2024-02-29"),by="14 day")
#scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"), as.Date("2024-02-26"))

#scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"))

FR_1 <- list()
# generate
for (i in 1:num_sims) {
  FR_1[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_1)
      )
    )
  )
}
as.numeric(FR_1[[1]]$case_reported[,11]) - as.numeric(FR_1[[1]]$case_true)
```


```{r}
# input list
FR_2 <- list()
# generate
for (i in 1:num_sims) {
  FR_2[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_2)
      )
    )
  )
}
```


```{r}
# input list
FR_3 <- list()
# generate
for (i in 1:num_sims) {
  FR_3[[i]] <- simulateData(
        params <- list(
      data = list(
        alpha_lamb = alpha_lamb,  
        beta_lamb  = beta_lamb,
        n_obs       = n_obs,
        date_start = as.Date("2024-01-01"),
        seed       = i
      ),
      reporting = list(
        D           = D,     
        D_complete        = D_complete,    
        if_fully_reported = if_fully_reported
      ),
      q_model = list(
        method        = method,
        method_params = list(alpha = alpha_ou, mu = mu_ou, 
                             b_init = b_init, sigma_ou = sigma_ou_3)
      )
    )
  )
}
```


## fit model
```{r}
time_2_s <- Sys.time()
out_list_1_FR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_1_FR[[i]] <- 
    nowcasting_moving_window(FR_1[[i]]$case_reported, scoreRange = scoreRange, 
                                case_true = FR_1[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T)
}
time_2 <- Sys.time() - time_2_s
#save(out_list_1_FR, file = file.path(path_proj, "data", "fitted_model", "simulation_ou", "FR_b01_sd001_sims5.RData"))
#load(file.path(path_proj,"data", "fitted_model", "simulation", "FR_b01_sd001.RData"))

# results_1_FR_plots <- nowcasts_plot(results_1_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```

```{r}
out_list_2_FR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_2_FR[[i]] <- 
    nowcasting_moving_window(FR_2[[i]]$case_reported, scoreRange = scoreRange, 
                                case_true = FR_2[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T)
}

#save(out_list_2_FR, file = file.path(path_proj, "data", "fitted_model", "simulation_ou", "FR_b01_sd01_sims5.RData"))
#load(file.path(path_proj,"data", "fitted_model", "simulation", "FR_b01_sd001.RData"))


# results_1_FR_plots <- nowcasts_plot(results_1_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```

```{r}
out_list_3_FR <- list()
for (i in 1:num_sims){
  print(paste0("Now is working on ",i,"th simulation."))
  out_list_3_FR[[i]] <- 
    nowcasting_moving_window(FR_3[[i]]$case_reported, scoreRange = scoreRange, 
                                case_true = FR_3[[i]]$case_true,
                                start_date = as.Date("2024-01-01"),
                                D = D, seeds = seed,
                                models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                                #models_to_run =c("fixed_q",  "ou_b"),
                                compiled_models = compiled_models,
                                iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                                num_chains = 3, suppress_output = T)
}

#save(out_list_3_FR, file = file.path(path_proj, "data", "fitted_model", "simulation_ou", "FR_b01_sd03_sims5.RData"))
#load(file.path(path_proj,"data", "fitted_model", "simulation", "FR_b01_sd001.RData"))


# results_1_FR_plots <- nowcasts_plot(results_1_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))
```

```{r}
results_1_FR <- compute_all_nowcasts_tables(out_list_1_FR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
results_1_FR_avg <- average_nowcasts_tables(results_1_FR)

plots_1_FR <- nowcasts_plot(
  nowcasts_list = results_1_FR_avg,
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = "Averaged Nowcasts Over All Replicates"
)

# Average metrics
metrics_1_FR_avg <- average_nowcasts_metrics(
  results_all   = results_1_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_1_FR_avg

# Average metrics
metrics_1_FR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_1_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_1_FR_avg_incomplete

#
# for (t in seq_along(metrics_1_FR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_1_FR_avg[[t]])
# }
```


```{r}
results_2_FR <- compute_all_nowcasts_tables(out_list_2_FR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
results_2_FR_avg <- average_nowcasts_tables(results_2_FR)

plots_2_FR <- nowcasts_plot(
  nowcasts_list = results_2_FR_avg,
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = "Averaged Nowcasts Over All Replicates"
)

# Average metrics
metrics_2_FR_avg <- average_nowcasts_metrics(
  results_all   = results_2_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_2_FR_avg

# Average metrics
metrics_2_FR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_2_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_2_FR_avg_incomplete


#
# for (t in seq_along(metrics_2_FR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_2_FR_avg[[t]])
# }
```

```{r}
results_3_FR <- compute_all_nowcasts_tables(out_list_3_FR, D, "day", c("fixed_q", "fixed_b", "linear_b", "ou_b"))

# plots
results_3_FR_avg <- average_nowcasts_tables(results_3_FR)

plots_3_FR <- nowcasts_plot(
  nowcasts_list = results_3_FR_avg,
  D = D,
  report_unit = "day",
  models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  combine_plots = TRUE,
  title = "Averaged Nowcasts Over All Replicates"
)

# Average metrics
metrics_3_FR_avg <- average_nowcasts_metrics(
  results_all   = results_3_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b")
)

metrics_3_FR_avg

# Average metrics
metrics_3_FR_avg_incomplete <- average_nowcasts_metrics(
  results_all   = results_3_FR,
  methods       = c("fixed_q", "fixed_b", "linear_b", "ou_b"),
  filter_length = D
)

metrics_3_FR_avg_incomplete


#
# for (t in seq_along(metrics_3_FR_avg)) {
#   cat("===== Window", t, "=====\n")
#   print(metrics_3_FR_avg[[t]])
# }
```


