---
title: "Sims"
author: "Yang Xiao"
date: "2024-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
```


```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "simulation", "simulations_functions_final.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))

# place for draws
path_to_draws_file = file.path("~", "Desktop", "draws")

```

```{r}
#models
fixed_q <- file.path(path_proj, "source", "models", "withIntercept",
                      "1.stan_model_fixed_q_trunc.stan")
fixed_b <- file.path(path_proj, "source", "models", "withIntercept",
                     "2.stan_model_fixed_b_trunc.stan")
linear_b <- file.path(path_proj, "source", "models", "withIntercept",
                     "3.stan_model_linear_b_trunc.stan")
ou_b <-  file.path(path_proj, "source", "models", "withIntercept",
                      "4.stan_model_ou_b_trunc.stan")

compiled_models <- list(
  fixed_q = cmdstan_model(fixed_q),
  fixed_b = cmdstan_model(fixed_b),
  linear_b = cmdstan_model(linear_b),
  ou_b = cmdstan_model(ou_b)
)
```


## simulate data - FR

### setting
```{r}
###### setting #####
seed <- 123
set.seed(seed)

# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10), 
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
n_obs = 60
# reprot structure
D <- 10; D_complete <- 20; if_fully_reported <- T

scoreRange <- c(as.Date("2024-01-29"),as.Date("2024-02-12"), as.Date("2024-02-26"))
```

```{r}
# fixed_q_FR
params_fixed_q_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = "fixed_q",
    method_params = list(q = generate_exponential_q(D, lambda = 0.3))
  )
)

fixed_q_FR <- simulateData(params_fixed_q_FR)
```

```{r}
# fixed_b_FR
params_fixed_b_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = "fixed_b",
    method_params = list(b = 0.4)
  )
)

fixed_b_FR <- simulateData(params_fixed_b_FR)
```

```{r}
# linear_b_FR
params_linear_b_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = "linear_b",
    method_params = list(beta0 = -2, beta1 = 0.05)
  )
)

linear_b_FR <- simulateData(params_linear_b_FR)
```

```{r}
# ou_FR
params_ou_b_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,  
    beta_lamb  = beta_lamb,
    n_obs       = n_obs,
    date_start = as.Date("2024-01-01"),
    seed       = seed
  ),
  reporting = list(
    D           = D,     
    D_complete        = D_complete,    
    if_fully_reported = if_fully_reported
  ),
  q_model = list(
    method        = "ou_b",
    method_params = list(alpha = 0.4, mu = 0.4, b_init = 0.4, sigma_ou = 0.1)
  )
)

ou_b_FR <- simulateData(params_ou_b_FR)
```


## fit model
```{r}
out_fixed_q_FR <- nowcasting_moving_window(fixed_q_FR$case_reported, scoreRange = scoreRange,
                          case_true = fixed_q_FR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T, 
                          #posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "testEachMethods")
                          posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "testEachMethods")
                          )


#save(out_list_1_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))

results_fixed_q_FR <- nowcasts_table(out_fixed_q_FR, D = D, report_unit = "day", 
                          models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"))

plots_fixed_q_FR <- nowcasts_plot(results_fixed_q_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))

for (i in 1:length(results_fixed_q_FR)) {
  print(calculate_metrics(results_fixed_q_FR[[i]]))
}
plots_fixed_q_FR
```   

```{r}
out_fixed_b_FR <- nowcasting_moving_window(fixed_b_FR$case_reported, scoreRange = scoreRange,
                          case_true = fixed_b_FR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T, 
                          #posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "testEachMethods")
                          posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "testEachMethods")
                          )


#save(out_list_1_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))

results_fixed_b_FR <- nowcasts_table(out_fixed_b_FR, D = D, report_unit = "day", 
                          models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"))

plots_fixed_b_FR <- nowcasts_plot(results_fixed_b_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))

for (i in 1:length(results_fixed_b_FR)) {
  print(calculate_metrics(results_fixed_b_FR[[i]]))
}
print(plots_fixed_b_FR)
```   

```{r}
out_linear_b_FR <-
  nowcasting_moving_window(linear_b_FR$case_reported, scoreRange = scoreRange,
                          case_true = linear_b_FR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T, 
                          #posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "testEachMethods")
                          posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "testEachMethods")
                          )


#save(out_list_1_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))

results_linear_b_FR <- nowcasts_table(out_linear_b_FR, D = D, report_unit = "day", 
                          models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"))

plots_linear_b_FR <- nowcasts_plot(results_linear_b_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))

for (i in 1:length(results_linear_b_FR)) {
  print(calculate_metrics(results_linear_b_FR[[i]]))
}
print(plots_linear_b_FR)
```   

```{r}
out_ou_b_FR <-
  nowcasting_moving_window(ou_b_FR$case_reported, scoreRange = scoreRange,
                          case_true = ou_b_FR$case_true,
                          start_date = as.Date("2024-01-01"),
                          D = D, seeds = seed,
                          models_to_run =c("fixed_q", "fixed_b", "linear_b", "ou_b"),
                          compiled_models = compiled_models,
                          iter_sampling = 2000, iter_warmup = 1000, refresh = 0,
                          num_chains = 3, suppress_output = T, 
                          #posterior_draws_path = file.path(Sys.getenv("HOME"), "Desktop", "draws", "testEachMethods")
                          posterior_draws_path = file.path(Sys.getenv("USERPROFILE"), "Desktop", "draws", "testEachMethods")
                          )


#save(out_list_1_NFR, file = file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))
#load(file.path(path_proj, "data", "fitted_model", "simulation", "NotFR_b01_sd001_sims5.RData"))

results_ou_b_FR <- nowcasts_table(out_ou_b_FR, D = D, report_unit = "day", 
                          models_to_run = c("fixed_q", "fixed_b", "linear_b", "ou_b"))

plots_ou_b_FR <- nowcasts_plot(results_ou_b_FR, D = D, report_unit = "day", models_to_run = c("fixed_q", "fixed_b", "linear_b" , "ou_b"))

for (i in 1:length(results_ou_b_FR)) {
  print(calculate_metrics(results_ou_b_FR[[i]]))
}
print(plots_ou_b_FR)
```   
