---
title: "Time-varying parametric reported probability: OU process"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
library(dplyr)
library(bayesplot)
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

source(file.path(path_source, "simulation", "simulations_functions_final.R"))
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "fit_function.R"))
source(file.path(path_source, "functions", "table_function.R"))
source(file.path(path_source, "functions", "prior_function.R"))
posterior_draws_path = file.path(path_proj, "data", "draws", "testEach")
```

```{r}
b_ou <-  file.path(path_proj, "source", "models", "b-ou.stan")
model <- cmdstan_model(b_ou)
```

## Fully reported scenario

### Setting

```{r}
# data
alpha_increase_seq_1 <- seq(10, 750, by = 30)
alpha_decrease_seq_1 <- seq(750, 10, by = -30)
alpha_lamb =  c( rep(10,5), alpha_increase_seq_1 + rnorm(alpha_increase_seq_1,10,10),
                 alpha_decrease_seq_1 + rnorm(alpha_decrease_seq_1,10,10),
                 rep(10,5))
beta_lamb = 0.5
T = 60
D <- 15;
```

### Simulation

```{r}
params_b_ou_FR <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "b_ou",
    method_params = list(theta_logb = 0.3, mu_logb = log(0.7), init_logb = log(0.7), sigma_logb = 0.2,
                         theta_logitphi = 0.3, mu_logitphi = 1, init_logitphi = 1, sigma_logitphi = 0.2)
  )
)
b_ou_FR <- simulateData(params_b_ou_FR)
par(mfrow = c(2, 1))
plot(b_ou_FR$b, pch = 19, type = "b")
plot(b_ou_FR$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(b_ou_FR$q), type = "l", lty = 1, ylim = c(0, 1))
```

### Exploratory analysis

```{r}
page_num <- ceiling(nrow(b_ou_FR$case_reported_cumulated)/16)
exp_plot_ou <- fit_exp_plot(b_ou_FR$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
exp_plot_ou$plots[[1]]
exp_plot_ou$plots[[4]]

exp_plot_ou$coefficients
exp_b_data_ou<- data.frame( date = as.Date(rownames(b_ou_FR$case_reported_cumulated)),
                          b = exp_plot_ou$coefficients$b)
exp_b_plot_ou <- ggplot(exp_b_data_ou, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +
  geom_smooth(method = "loess", se = TRUE,
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")
print(exp_b_plot_ou)
```

### Model fitting

```{r}
ind = 40
hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
stan_data <- c(list(T = ind, D = 15, Y = b_ou_FR$case_reported_cumulated[1:ind, ]), hypers)

test = model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 2000,
    chains = 1,
    refresh = 0,
    thin = 1)
varnames <- test$summary()$variable

mcmc_areas(test$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true = tibble(
    parameter = grep("^b\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_FR$b[1:ind]
)
mcmc_areas(test$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^phi\\[.+\\]$", varnames, value = TRUE),
    x = 1 - b_ou_FR$phi[1:ind]
)
mcmc_areas(test$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_FR$lambda[1:ind]
)
mcmc_areas(test$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames, value = TRUE),
    x = b_ou_FR$q[10,]
)
mcmc_areas(test$draws(grep("^q\\[10,.+\\]$", varnames, value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_FR$case_true[1:ind, 1]
)
mcmc_areas(test$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)
```

## Non-fully reported scenario

### Simulation

```{r}
# ou_NFR
params_b_ou_NFR <- list(
  data = list(
    alpha_lamb = alpha_lamb,
    beta_lamb  = beta_lamb,
    T       = T,
    date_start = as.Date("2024-01-01"),
    D = D
  ),
  q_model = list(
    method        = "b_ou",
    method_params = list(theta_logb = 0.2, mu_logb = log(0.2), init_logb = log(0.2), sigma_logb = 0.15,
                         theta_logitphi = 0.2, mu_logitphi = 1.5, init_logitphi = 1.5, sigma_logitphi = 0.15)
  )
)

b_ou_NFR <- simulateData(params_b_ou_NFR)
par(mfrow = c(2, 1))
plot(b_ou_NFR$b, pch = 19, type = "b")
plot(b_ou_NFR$phi, pch = 19, type = "b")

par(mfrow = c(1, 1))
matplot(t(b_ou_NFR$q), type = "l", lty = 1, ylim = c(0, 1))
```

### Exploratory analysis

```{r}
page_num <- ceiling(nrow(b_ou_NFR$case_reported_cumulated)/16)
exp_plot_rw_b <- fit_exp_plot(b_ou_NFR$case_reported_cumulated,ncol = 4, nrow = 4, page = c(1:page_num), if_fit = T)
print(exp_plot_rw_b)

exp_plot_rw_b$coefficients
exp_b_data_rw_b<- data.frame( date = as.Date(rownames(b_ou_NFR$case_reported_cumulated)),
                          b = exp_plot_rw_b$coefficients$b)
exp_b_plot_rw_b <- ggplot(exp_b_data_rw_b, aes(x = date, y = b)) +
  geom_point(color = "black", size = 1.5) +
  geom_smooth(method = "loess", se = TRUE,
              color = "blue", fill = "grey", alpha = 0.5) +
  theme_minimal() +
  labs(x = NULL, y = "Y", title = "Smoothed Curve of parameter b")
print(exp_b_plot_rw_b)
```

### Model fitting

```{r}
ind = 40
hypers = hypers_q(phi_ref = 0.2, D_ref = 15, type = "exponential", alpha_phi = 1.4, sd_log_b = 1, delay_seq = 0:15)
stan_data <- c(list(T = ind, D = 15, Y = b_ou_NFR$case_reported_cumulated[1:ind, ]), hypers)

test = model$sample(
    data = stan_data,
    iter_sampling = 3000,
    iter_warmup = 3000,
    chains = 1,
    refresh = 0,
    thin = 1)
varnames <- test$summary()$variable

mcmc_areas(test$draws("sigma_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("sigma_logit_phi"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("theta_logit_phi"), prob = 0.95, prob_outer = 0.95)

mcmc_areas(test$draws("mu_log_b"), prob = 0.95, prob_outer = 0.95)
mcmc_areas(test$draws("mu_logit_phi"), prob = 0.95, prob_outer = 0.95)


param_true = tibble(
    parameter = grep("^b\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_NFR$b[1:ind]
)
mcmc_areas(test$draws("b"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^phi\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_NFR$phi[1:ind]
)
mcmc_areas(test$draws("phi"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^lambda\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_NFR$lambda[1:ind]
)
mcmc_areas(test$draws("lambda"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^q\\[10,.+\\]$", varnames, value = TRUE),
    x = b_ou_NFR$q[10,]
)
mcmc_areas(test$draws(grep("^q\\[10,.+\\]$", varnames, value = TRUE)), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)

param_true = tibble(
    parameter = grep("^N\\[.+\\]$", varnames, value = TRUE),
    x = b_ou_NFR$case_true[1:ind, 1]
)
mcmc_areas(test$draws("N"), prob_outer = 0.95) +
    geom_point(aes(x = x), param_true, color = "red", size = 1)
```

```{r}
# 1. Label the matrix columns as delays 0,1,…,15
n_delays <- ncol(b_ou_NFR$q)
colnames(b_ou_NFR$q) <- as.character(0:(n_delays-1))

# 2. Convert to data.frame and add a time index
df <- as.data.frame(b_ou_NFR$q) %>%
  mutate(time = row_number())

# 3. Pivot to long format
df_long <- df %>%
  pivot_longer(
    cols      = -time,
    names_to  = "delay",
    values_to = "q"
  ) %>%
  mutate(delay = as.integer(delay))

# 4. Plot with ggplot2
ggplot(df_long, aes(x = delay, y = q, group = time)) +
  geom_line(
    colour = "red",  # a muted academic red
    size   = 0.7,
    alpha  = 0.6
  ) +
  scale_x_continuous(breaks = 0:15, limits = c(0, 15)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2), limits = c(0, 1)) +
  labs(
    x     = "Delay (d)",
    y     = expression(q[t](d)),
    title = NULL
  ) +
  theme_classic(base_size = 14)
```

