---
title: "MovingWindowSims"
author: "Yang Xiao"
date: "2024-11-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rstan)
# library(cmdstanr)
library(splines)
library(ggplot2)
library(reshape2)
```

```{r}
path_proj = here::here()
path_source = file.path(path_proj, "source")

# source
source(file.path(path_source, "simulation", "simulations_functions_final.R"))

# source from other paper
source(file.path(path_source, "funcs_german_paper", "plotReportingTriangle.R"))
```

```{r}
# setting: delay,  number of days
seed <- 4
D <- 15
N_obs <- 200

# generate alpha
alpha_lambda <- generate_alpha(N_obs, range = c(40, 200), dist = "uniform", seed = seed)
plot(density(alpha_lambda))
```

```{r}
# time varying b
beta0 = -2 ; beta1 = 0.01
data <- simsDataGenQ( alpha = alpha_lambda,
                     #alpha =  c(1:10, seq(1, 232, by = 4)),
                      days = N_obs, method = "random_walk",
                     b = 0.1, sigma_rw = 0.1, seed = seed)
data
# create triangular data
data_trunc <- create_triangular_data(data$case_reported)

# get indices of non-NAs 
indices_data_trunc <- find_non_na_coords(data_trunc)

data_trunc[is.na(data_trunc)] <- 0  

print(data_trunc)
```
### basis for spline
```{r}
# setting
time_points <- 1:N_obs
n_knots <- 5

# create basis
X_spline <- create_basis(N_obs, n_knots)

basis_df <- data.frame(time = time_points, X_spline)
basis_long <- reshape2::melt(basis_df, id.vars = "time")

# draw basis
ggplot(basis_long, aes(x = time, y = value, color = variable)) +
  geom_line() +
  labs(title = "B-spline Basis Functions for Time",
       x = "Time (Days)",
       y = "Basis Value") +
  theme_minimal()
```
```{r}
source(file.path(path_source, "functions", "plot_function.R"))
source(file.path(path_source, "functions", "moving_window_function.R"))
# imagine 60 days since 2024-01-01

# now <- as.Date("2024-02-01")
scoreRange <- seq(as.Date("2024-01-20"),as.Date("2024-02-28"),by="1 day")

path_p_change <- file.path(path_proj, "source", "models",
                     "trunc", "stan_model_dep-spline-trunc-modi.stan")

path_p_fixed <- file.path(path_proj, "source", "models", "trunc",
                     "stan_model_time-ind-p-trunc.stan")

dates <- seq(as.Date("2024-01-20"),as.Date("2024-07-18"),by="1 day")  # 40days
selected_dates <- dates[c(200)]  # pick certain days

out <- nowcasting_moving_window(data$case_reported, selected_dates,
                         N_obs = N_obs, D = 15, sigma_b = 0.1, seeds = 123,
                         iter= 10000, warmup = 2000,
                         path_p_change = path_p_change, path_p_fixed = path_p_fixed)
data <- data$case_reported
```

```{r}
out$plots
```

```{r}
# real data
real_data_path <- normalizePath(file.path(path_source, "..", "data", "raw")) # data path

load(file.path(real_data_path,"husO104Hosp.Rdata"))
husO104_triangular <- listToTriangle(husO104Hosp)
husO104_tri_cumu <- cumulative_matrix(husO104_triangular)

selected_dates <- seq(as.Date("2011-05-20"),as.Date("2011-06-30"),by="5 day")

out <- nowcasting_moving_window(husO104_tri_cumu, scoreRange = selected_dates,
                                case_true = as.vector(husO104_tri_cumu[,ncol(husO104_tri_cumu)]),
                         N_obs = nrow(husO104_tri_cumu), D = 15, sigma_b = 0.1, seeds = 123,
                         iter= 3000, warmup = 1500, num_chains = 3, if_real_data = T,
                         path_p_change = path_p_change, path_p_fixed = path_p_fixed)
out$plots
```

```{r}
data_temp <- simsDataGenQ( alpha = c(1:30),
                     #alpha =  c(1:10, seq(1, 232, by = 4)),
                      days = 30, method = "random_walk",
                     b = 0.1, sigma_rw = 0.1, seed = seed)
data_tri <- create_triangular_data(data_temp$case_reported, if_zero = T)
data_tri
sum(data_tri)

list_temp <- triangleToList(data_tri, now = as.Date("2024-07-31"))

data <- list_temp



extract_last_valid(mat, D = 4)
print("Input Matrix:")
print(input_matrix)

output_matrix <- cumulative_matrix(input_matrix)
print(output_matrix)

output_matrix[, ncol(output_matrix)]
```


